### ISSUE TITLE
Not working with 223

### ISSUE THREAD

**Issue by SamD** [zzehring/intellij-jsonnet#27]
Tried bumping the version which allowed it to load with no exceptions but doesn't seem to work

**Comment by zzehring** [comment]
So it sounds like plugin is working but the language server/language server functionality is not. When you open a `.jsonnet`/`.libsonnet` file, does a green/red/yellow circle appear on your bottom toolbar? Ex:

![image](https://user-images.githubusercontent.com/7545035/201136339-d05b2d15-ffc5-4514-827f-e1c4c6076e6f.png)

Also, was it a bump to the plugin version or the language server version? The update feature for the language server binary itself can have issues but it would surface an error.

**Comment by sergeyshevch** [comment]
I guess it's more about the IDE verion.
Not compatible with the version of your running IDE (GoLand 2022.3.1)

**Comment by atombender** [comment]
I'm not even able to activate it:

![Screenshot 2023-01-03 at 11 49 06](https://user-images.githubusercontent.com/50314/210342902-9872dc19-925d-4512-9755-56f27034bee9.jpg)

My version:

```
IntelliJ IDEA 2022.3.1 (Ultimate Edition)
Build #IU-223.8214.52, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0.1
```

**Comment by zzehring** [comment]
223.* IDEs should be working with the new v0.0.10 release. The update should be available on plugin store tomorrow.

**Comment by zzehring** [comment]
Hey ya'll. So v0.0.10 allowed the plugin to work in 223.* IDEs but the Jsonnet Language server wasn't being started (due to deprecation/removal of startup activity extension). v0.1.0 was released today which includes a change to use the new method for starting up/handling the language server. You can review the fix in [this PR](https://github.com/zzehring/intellij-jsonnet/pull/34).

So far it's working for me on 2022.3.1 (build #GO-223.8214.59). So marking this one as resolved. I apologize for taking so long on fix. Feel free to reopen if it's not working for some 223.* version. And of course, any other problems please open up another issue.
